[package]
name = "reaper"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47", features = ["macros", "rt-multi-thread"] }
metrics = { version = "0.24" }
metrics-exporter-prometheus = { version = "0.17" }
tracing = { version = "0.1" }
tracing-opentelemetry = { version = "0.31" }
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
serenity = { version = "0.12", features = ["collector"] }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "time", "uuid"] }
time = { version = "0.3", features = ["large-dates"] }
redis = { version = "0.32", features = ["tokio-comp"] }
inflections = { version = "1.1" }
async-trait = { version = "0.1" }
humantime = { version = "2.2" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
uuid = { version = "1.18", features = ["v4", "serde"] }
dashmap = { version = "6.1" }
regex = { version = "1.11" }
strum = { version = "0.27", features = ["derive"] }
ordinal = { version = "0.4" }