name: reaper

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - bot_network
      - metrics_network
    environment:
      - PROMETHEUS_PORT
      - DB_USER
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME
      - DB_HOST
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    ports:
      - "9000:9000"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
        reservations:
          memory: 128M
          cpus: "0.2"

  database:
    image: postgres:15.3
    restart: unless-stopped
    networks:
      - bot_network
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2.5
    restart: unless-stopped
    command: redis-server --save 20 1 --requirepass ${REDIS_PASSWORD}
    networks:
      - bot_network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    networks:
      - metrics_network
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    networks:
      - metrics_network
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana_provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

networks:
  bot_network:
    driver: bridge
  metrics_network:
    driver: bridge

volumes:
  database_data:
    driver: local
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local