name: reaper
services:
  bot:
    build:
      context: .
    restart: unless-stopped
    networks:
      - database
    environment:
      - DISCORD_TOKEN=[TOKEN]
      - DB_USER=[USERNAME]
      - DB_PASSWORD=[PASSWORD]
      - DB_HOST=database
      - DB_NAME=[NAME]
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=[PASSWORD]
    depends_on:
      - database
  database:
    image: postgres:15.3
    restart: unless-stopped
    networks:
      - database
    environment:
      - POSTGRES_USER=[USERNAME]
      - POSTGRES_PASSWORD=[PASSWORD]
    ports:
      - 5432:5432
    volumes: 
      - database:/var/lib/postgresql/data
  redis:
    image: redis:6.2.5
    restart: unless-stopped
    command: redis-server --save 20 1 --requirepass [PASSWORD]
    networks:
      - database
    ports:
      - 6379:6379
    volumes:
      - redis:/data
networks:
  database: {}
volumes:
  database:
    driver: local
  redis:
    driver: local