global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'discord_bot'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['bot:9000']
        labels:
          application: discord-bot

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']