-- Add migration script here
ALTER TABLE giveaways ADD COLUMN host BIGINT NOT NULL DEFAULT 1038868171387580456;
ALTER TABLE giveaways ADD COLUMN image_url TEXT NULL;
ALTER TABLE giveaways ADD COLUMN color INTEGER NULL;